# Profile startup time https://esham.io/2018/02/zsh-profiling
# zmodload zsh/datetime
# setopt PROMPT_SUBST
# PS4='+$EPOCHREALTIME %N:%i> '
# logfile=$(mktemp ~/zshprofile/zsh_profile.XXXXXXXX)
# echo "Logging to $logfile"
# exec 3>&2 2>$logfile
# setopt XTRACE

## $PATH related things
export PATH="$HOME/homebrew/sbin:$HOME/homebrew/bin:$PATH"
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/Users/jamesroutley/homebrew/opt/go@1.8/bin:$PATH"
export PATH="$HOME/.config/bin:$PATH"
export PATH="$HOME/hacks:$PATH"
export PATH="/Applications/Racket v7.9/bin:$PATH"


# Use homebrew python instead of system python
if [ -d "/Users/jamesroutley/homebrew/opt/python/libexec/bin" ]; then
    export PATH="/Users/jamesroutley/homebrew/opt/python/libexec/bin:$PATH"
fi

export PATH="/Users/jamesroutley/homebrew/opt/python@2/libexec/bin:$PATH"

export HOMEBREW_CASK_OPTS="--appdir=~/Applications"


## ZSH customisation

eval "$(starship init zsh)"

# Enable zsh vim mode
set -o vi

# Arrow-key autocomplete selection
zstyle ':completion:*' menu select

# Set up history: https://unix.stackexchange.com/a/111777
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000


## Aliases

# Add ls options. all, long, human-readable, slashes after directories
alias ll='ls -hlGFA'

# Git aliases:
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gd="git diff"
alias gdc="git diff --cached"
alias gcne="git commit --amend --no-edit"
alias gp="git push"
gpn() {
    local remote=$(git config --get remote.origin.url)
    local repo=$(basename -s .git "$remote")

    git push --set-upstream origin $(git branch --show-current) && open https://github.com/avianlabs/$repo/pull/new/$(git branch --show-current)
}
gwip() {
    git add .
    git commit -m "WIP"
}
grm() {
    git fetch origin
    git rebase origin/master
}

alias fdb="flexdebug"
alias fdbs="flexdebug -e s101"

## Tool customisation

# Make nvim the default editor, if it exists
if command -v nvim &>/dev/null
then
	export EDITOR="nvim"
else
	export EDITOR="vim"
fi

# Enable git completion (maybe this enables autocompletion generally?)
autoload -Uz compinit && compinit

# Coloured ls output
export CLICOLOR=1

# Set up FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


## Helper functions

# Git Ignore Generator
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# Serve go documentation
function gwd () {
    echo "Listening on localhost:5001"
    godoc -http :5001 &
    open 'http://localhost:5001'
    echo "Kill server with:"
    echo "kill" $!
}


## Laptop-specific setup
[ -f $HOME/.config/zsh/personal.sh ] && source $HOME/.config/zsh/personal.sh

# Set up Monzo specific things
[ -f $HOME/.config/zsh/sling.sh ] && source $HOME/.config/zsh/sling.sh


[ -f /Users/jamesroutley/code/mz/analytics/dbt/misc/shell/source.sh ] && source /Users/jamesroutley/code/mz/analytics/dbt/misc/shell/source.sh
export PYENV_ROOT=/usr/local/var/pyenv
export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jamesroutley/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jamesroutley/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jamesroutley/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jamesroutley/google-cloud-sdk/completion.zsh.inc'; fi

function j64() {echo "$1" | base64 -D | jq}

function jraw() {echo "$1" | jq -r | jq}

# Stop profiling startup time.
# unsetopt XTRACE
# exec 2>&3 3>&-
# source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
# source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

export NVM_DIR="$HOME/.nvm"
[ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && . "$(brew --prefix)/opt/nvm/nvm.sh" # This loads nvm
[ -s "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" ] && . "$(brew --prefix)/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
[ -f $HOME/src/github.com/monzo/starter-pack/zshrc ] && source $HOME/src/github.com/monzo/starter-pack/zshrc
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"

source <(cli completion zsh)

function uid() {
    uuidgen | tr -d '\n' | pbcopy
    echo "Copied to clipboard"
}

alias userp="echo -n user_cd7vnhve018ks38sl6tg | pbcopy && echo 'Copied to clipboard'"
alias users="echo -n user_ch8igtucnq6qpt0et880 | pbcopy && echo 'Copied to clipboard'"

eval "$(atuin init zsh)"

export RIPGREP_CONFIG_PATH="$HOME/.config/.ripgreprc"
