## $PATH related things
export PATH="$HOME/homebrew/sbin:$HOME/homebrew/bin:$PATH"
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/Users/jamesroutley/homebrew/opt/go@1.8/bin:$PATH"
export PATH="$HOME/.config/bin:$PATH"
export PATH="$HOME/hacks:$PATH"

# Use homebrew python instead of system python
if [ -d "/Users/jamesroutley/homebrew/opt/python/libexec/bin" ]; then
    export PATH="/Users/jamesroutley/homebrew/opt/python/libexec/bin:$PATH"
fi

export PATH="/Users/jamesroutley/homebrew/opt/python@2/libexec/bin:$PATH"

export HOMEBREW_CASK_OPTS="--appdir=~/Applications"


## ZSH customisation

eval "$(starship init zsh)"

# Enable zsh vim mode
set -o vi

# Arrow-key autocomplete selection
zstyle ':completion:*' menu select

# Set up history: https://unix.stackexchange.com/a/111777
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000


## Aliases

# Add ls options. all, long, human-readable, slashes after directories
alias ll='ls -hlGFA'

# Git aliases:
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"


## Tool customisation

# Make nvim the default editor, if it exists
if command -v nvim &>/dev/null
then
	export EDITOR="nvim"
else
	export EDITOR="vim"
fi

# Enable git completion (maybe this enables autocompletion generally?)
autoload -Uz compinit && compinit

# Coloured ls output
export CLICOLOR=1

# Set up FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


## Helper functions

# Git Ignore Generator
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# Serve go documentation
function gwd () {
    echo "Listening on localhost:5001"
    godoc -http :5001 &
    open 'http://localhost:5001'
    echo "Kill server with:"
    echo "kill" $!
}


## Laptop-specific setup
[ -f $HOME/.config/zsh/personal.sh ] && source $HOME/.config/zsh/personal.sh

# Set up Monzo specific things
[ -f $HOME/.config/zsh/monzo.sh ] && source $HOME/.config/zsh/monzo.sh


[ -f /Users/jamesroutley/code/mz/analytics/dbt/misc/shell/source.sh ] && source /Users/jamesroutley/code/mz/analytics/dbt/misc/shell/source.sh
